import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Injectable } from '@angular/core';

// mock data generated by ChatGPT
const data = [
  {
    name: 'Spaghetti Bolognese',
    ingredients:
      'spaghetti, ground beef, onion, garlic, canned tomatoes, red wine, olive oil, salt, pepper, basil',
    instructions:
      '1. Cook spaghetti according to package instructions. 2. In a separate pan, heat olive oil and sauté onion and garlic until softened. 3. Add ground beef and cook until browned. 4. Pour in canned tomatoes and red wine, bring to a simmer and let cook for 10 minutes. 5. Season with salt, pepper, and basil. 6. Serve the bolognese sauce over cooked spaghetti. ',
    image: 'https://spaghetti-bolognese.jpg',
    tags: 'italian, main course, beef',
    rating: 4.5,
    notes: '',
    source: "Grandma's cookbook",
    date: '2022-12-01',
    id: 1,
  },
  {
    name: 'Veggie Stir Fry',
    ingredients:
      'rice, mixed vegetables, soy sauce, ginger, garlic, sesame oil, red pepper flakes',
    instructions:
      '1. Cook rice according to package instructions. 2. In a wok or large pan, heat sesame oil and add mixed vegetables. Stir fry until tender. 3. Add ginger, garlic, and red pepper flakes and stir for another minute. 4. Pour in soy sauce and stir to coat the vegetables. 5. Serve the stir fry over cooked rice. ',
    image: 'https://veggie-stir-fry.jpg',
    tags: 'asian, vegetarian, quick',
    rating: 4.0,
    notes: '',
    source: 'Online recipe',
    date: '2022-11-15',
    id: 2,
  },
  {
    name: 'Chocolate Chip Cookies',
    ingredients:
      'flour, sugar, brown sugar, butter, eggs, vanilla extract, baking soda, salt, chocolate chips',
    instructions:
      '1. Preheat oven to 375°F (190°C). 2. In a large bowl, cream together butter, sugar, and brown sugar until light and fluffy. 3. Beat in eggs and vanilla extract. 4. In a separate bowl, whisk together flour, baking soda, and salt. 5. Gradually add the dry ingredients to the wet mixture and mix until just combined. 6. Fold in the chocolate chips. 7. Scoop tablespoon-sized balls of dough onto a baking sheet lined with parchment paper. 8. Bake for 8-10 minutes, or until the edges are golden brown. ',
    image: 'https://chocolate-chip-cookies.jpg',
    tags: 'dessert, cookies, chocolate',
    rating: 5.0,
    notes: '',
    source: "Mom's recipe box",
    date: '2022-07-20',
    id: 3,
  },
  {
    name: 'Grilled Cheese Sandwich',
    ingredients: 'bread, cheese, butter',
    instructions:
      '1. Heat a pan over medium heat. 2. Butter one side of two slices of bread. 3. Place one slice of bread, butter side down, in the pan. 4. Top with cheese and the other slice of bread, butter side up. 5. Cook until the bread is golden brown and the cheese is melted, about 3-4 minutes on each side. ',
    image: 'https://grilled-cheese-sandwich.jpg',
    tags: 'sandwich, grilled cheese, lunch',
    rating: 4.0,
    notes: '',
    source: 'Classic cookbook',
    date: '2022-09-01',
    id: 4,
  },
  {
    name: 'Pancakes',
    ingredients:
      'flour, sugar, baking powder, salt, milk, eggs, melted butter, vanilla extract',
    instructions:
      '1. In a large bowl, whisk together flour, sugar, baking powder, and salt. 2. In a separate bowl, beat together milk, eggs, melted butter, and vanilla extract. 3. Gradually add the wet mixture to the dry mixture, stirring just until combined. 4. Heat a nonstick pan over medium heat. 5. Pour 1/4 cup of batter onto the pan for each pancake. 6. Cook until the edges start to dry and bubbles form on the surface, about 2-3 minutes. 7. Flip the pancake and cook for another 1-2 minutes. 8. Serve with syrup and butter. ',
    image: 'https://pancakes.jpg',
    tags: 'breakfast, pancakes, syrup',
    rating: 4.5,
    notes: '',
    source: "Grandpa's kitchen",
    date: '2022-06-01',
    id: 5,
  },
  {
    name: 'Lemon Chicken',
    ingredients:
      'chicken breasts, lemon juice, lemon zest, garlic, olive oil, salt, pepper',
    instructions:
      '1. In a large bowl, whisk together lemon juice, lemon zest, garlic, olive oil, salt, and pepper. 2. Add chicken breasts and marinate for at least 30 minutes. 3. Preheat oven to 375°F (190°C). 4. Place the chicken in a baking dish and pour the marinade over it. 5. Bake for 25-30 minutes, or until the chicken is cooked through. 6. Serve with roasted vegetables or a side salad. ',
    image: 'https://lemon-chicken.jpg',
    tags: 'chicken, lemon, main course',
    rating: 4.0,
    notes: '',
    source: "Friend's recipe",
    date: '2022-05-15',
    id: 6,
  },
];
@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const recipes = data;
    return { recipes };
  }
}
