import { Component } from '@angular/core';
import { Inject } from '@angular/core';
import {
  MAT_DIALOG_DATA,
  MatDialogRef,
  MatDialog
} from '@angular/material/dialog';
import { Recipe, Ingredient } from '../../recipe.model';


// ----------------- Button -----------------

@Component({
  selector: 'app-open-form-button',
  templateUrl: 'open-form-button.component.html',
})

export class OpenFormButtonComponent{
  id!: number;
  date!: Date;
  name!: string;
  ingredients!: string;
  instructions!: string;
  image!: string;
  tags!: string;
  rating!: number;
  notes!: string;
  source!: string;

  constructor(public dialog: MatDialog) {}

  openDialog(): void {
    const dialogRef = this.dialog.open(RecipeFormDialog, {
      width: '50vw',
      minWidth: '400px',
      data: {
        // TODO: determine if this is necessary -- I think ID is generated by the database
        id: this.id,
        date: new Date(),
        name: this.name,
        // TODO: split ingredients string into array of Ingredients objects
        ingredients: this.ingredients,
        // TODO: split instructions string into array of strings
        instructions: this.instructions,
        // TODO: handle empty optional fields
        image: this.image,
        tags: this.tags,
        rating: this.rating,
        notes: this.notes,
        source: this.source,
      },
    });

    dialogRef.afterClosed().subscribe((result) => {
      console.log(`Add Recipe Form closed:
        ${(result == undefined) 
          ? "Nothing submitted" 
          : `Added recipe with id # ${result.id}
          date: ${result.date.toLocaleString()}
          name: ${result.name}
          ingredients: ${result.ingredients}
          instructions: ${result.instructions}
          image: ${result.image}
          tags: ${result.tags}
          rating: ${result.rating}
          notes: ${result.notes}
          source: ${result.source}`  
        }`);
    });
  }
}

// ----------------- [Populate] Form -----------------
@Component({
  selector: 'recipe-form',
  templateUrl: 'recipe-form.component.html',
  styleUrls: ['../form.component.scss']
})

export class RecipeFormDialog {
  constructor(
    public dialogRef: MatDialogRef<RecipeFormDialog>,
    @Inject(MAT_DIALOG_DATA) public data: Recipe
  ) {}

  onNoClick(): void {
    this.dialogRef.close();
  }
}